# Generated by Django 4.2.28 on 2026-07-18 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_eau', models.CharField(choices=[('eau_potable', 'Eau potable'), ('industrielle', 'Industrielle')], max_length=20)),
                ('prix_litre', models.FloatField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_total', models.FloatField()),
                ('montant', models.FloatField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('en_retard', 'En retard')], default='en_attente', max_length=20)),
                ('mode_paiement', models.CharField(blank=True, choices=[('agence', 'Agence'), ('wave', 'Wave'), ('orange_money', 'Orange Money')], max_length=20, null=True)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateField()),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to=settings.AUTH_USER_MODEL)),
                ('tarif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factures.tarif')),
            ],
            options={
                'ordering': ['-date_generation'],
            },
        ),
    ]
