# Generated by Django 4.2.28 on 2026-08-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='periode_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='periode_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
