# Generated by Django 4.2.28 on 2026-08-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_facture_periode_debut_facture_periode_fin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarif',
            options={'verbose_name': 'Tarif', 'verbose_name_plural': 'Tarifs'},
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='prix_litre',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='type_eau',
        ),
        migrations.AddField(
            model_name='tarif',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tarif',
            name='prix_td',
            field=models.FloatField(default=878.35, help_text='Tranche dissuasive >40 m³ (FCFA/m³ TTC)'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='prix_tp',
            field=models.FloatField(default=697.97, help_text='Tranche progressive 21-40 m³ (FCFA/m³ TTC)'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='prix_ts',
            field=models.FloatField(default=202, help_text='Tranche sociale 0-20 m³ (FCFA/m³ TTC)'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='type_abonne',
            field=models.CharField(choices=[('domestique_15mm', 'Domestique diamètre 15mm'), ('domestique_20mm', 'Domestique diamètre >= 20mm'), ('non_domestique', 'Non domestique'), ('maraicher', 'Maraîcher')], default='domestique_15mm', max_length=20),
        ),
        migrations.AddField(
            model_name='tarif',
            name='type_zone',
            field=models.CharField(choices=[('assainie', 'Zone assainie'), ('non_assainie', 'Zone non assainie')], default='assainie', max_length=20),
        ),
    ]
