# Generated by Django 4.2.28 on 2026-07-18 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compteur', models.CharField(max_length=50, unique=True)),
                ('serie', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('attribue', 'Attribué'), ('en_panne', 'En panne')], default='disponible', max_length=20)),
                ('etat_vanne', models.CharField(choices=[('ouverte', 'Ouverte'), ('fermee', 'Fermée')], default='ouverte', max_length=10)),
                ('date_installation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compteurs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compteur',
                'verbose_name_plural': 'Compteurs',
            },
        ),
    ]
