# Generated by Django 4.2.28 on 2026-08-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compteurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteur',
            name='ferme_par',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('client', 'Client'), ('systeme', 'Système')], max_length=20, null=True),
        ),
    ]
