# Generated by Django 4.2.28 on 2026-09-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compteurs', '0002_compteur_ferme_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteur',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compteur',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
