# Generated by Django 4.2.28 on 2026-08-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='date_reponse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avis',
            name='reponse_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
