# Generated by Django 4.2.28 on 2026-08-01 02:10

from django.db import migrations, models
import utilisateurs.models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_utilisateur_options_utilisateur_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=utilisateurs.models.chemin_photo),
        ),
    ]
