# Generated by Django 4.2.28 on 2026-08-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_utilisateur_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='doc_attestation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='doc_cin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='doc_contrat_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='doc_convention',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='statut_abonnement',
            field=models.CharField(choices=[('actif', 'Actif'), ('en_traitement', 'En cours de traitement'), ('suspendu', 'Suspendu'), ('resilie', 'Résilié')], default='actif', max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='type_client',
            field=models.CharField(blank=True, choices=[('proprietaire', 'Propriétaire'), ('locataire', 'Locataire')], max_length=20, null=True),
        ),
    ]
