# Generated by Django 4.2.28 on 2026-07-18 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compteurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ouvrir', 'Ouvrir vanne'), ('fermer', 'Fermer vanne')], max_length=10)),
                ('statut', models.CharField(choices=[('envoyee', 'Envoyée'), ('executee', 'Exécutée'), ('echouee', 'Échouée')], default='envoyee', max_length=10)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='compteurs.compteur')),
                ('effectuee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('fuite', 'Fuite probable'), ('surconsommation', 'Surconsommation'), ('deconnecte', 'Compteur déconnecté')], max_length=20)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('resolue', 'Résolue')], default='en_cours', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='compteurs.compteur')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
