# Generated by Django 4.2.28 on 2026-08-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('fuite', 'Fuite '), ('surconsommation', 'Surconsommation'), ('deconnecte', 'Compteur déconnecté')], max_length=20),
        ),
    ]
