# Generated by Django 4.2.28 on 2026-08-12 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('zone', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('type_client', models.CharField(choices=[('proprietaire', 'Propriétaire'), ('locataire', 'Locataire')], default='proprietaire', max_length=20)),
                ('photo_cin', models.ImageField(blank=True, null=True, upload_to='demandes/cin/')),
                ('photo_attestation', models.ImageField(blank=True, null=True, upload_to='demandes/attestations/')),
                ('photo_contrat', models.ImageField(blank=True, null=True, upload_to='demandes/contrats/')),
                ('photo_convention', models.ImageField(blank=True, null=True, upload_to='demandes/conventions/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('motif_refus', models.TextField(blank=True, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'abonnement",
                'verbose_name_plural': "Demandes d'abonnement",
                'ordering': ['-date_demande'],
            },
        ),
    ]
