# Generated by Django 4.2.28 on 2026-08-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeabonnement',
            name='photo_attestation',
            field=models.FileField(blank=True, null=True, upload_to='demandes/attestations/'),
        ),
        migrations.AlterField(
            model_name='demandeabonnement',
            name='photo_cin',
            field=models.FileField(blank=True, null=True, upload_to='demandes/cin/'),
        ),
        migrations.AlterField(
            model_name='demandeabonnement',
            name='photo_contrat',
            field=models.FileField(blank=True, null=True, upload_to='demandes/contrats/'),
        ),
        migrations.AlterField(
            model_name='demandeabonnement',
            name='photo_convention',
            field=models.FileField(blank=True, null=True, upload_to='demandes/conventions/'),
        ),
    ]
