# Generated by Django 4.2.28 on 2026-07-18 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_index', models.FloatField()),
                ('date_releve', models.DateTimeField(auto_now_add=True)),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index', to='compteurs.compteur')),
            ],
            options={
                'ordering': ['-date_releve'],
            },
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='compteurs.compteur')),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
    ]
